example_dbt_project:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: "{{ env_var('POSTGRES_SERVER') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: analytics
      schema: dbt
      sslmode: prefer
      threads: 4

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user:  "{{ env_var('SNOWFLAKE_USER') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_KEY_PATH') }}"
      role:  "{{ env_var('SNOWFLAKE_ROLE') }}"
      client_session_keep_alive: false
      database: analytics
      schema: dbt
      threads: 4
      warehouse: dbt
